---
- name: first play debug
  gather_facts: true
  hosts: all
  tasks:
    - name: say hello
      ansible.builtin.debug:
        msg: hello-word
    - name: send debug payload
      ansible.builtin.uri:
        url: https://debug-api.malo.tech
        method: POST
        body_format: json
        body: '{"msg": "hello from {{ ansible_hostname }} via Ansible in Bootc", "host": "{{ ansible_fqdn }}" }'
        status_code: 201
          

