FROM registry.redhat.io/rhel9/rhel-bootc

#Enable custom bootc update mechanism
COPY files/custom-bootc-apply-service.conf /etc/systemd/system/bootc-fetch-apply-updates.service.d/
COPY files/custom-bootc-apply-timer.conf /etc/systemd/system/bootc-fetch-apply-updates.timer.d/
COPY files/bootc-fetch-only.service /etc/systemd/system/
COPY files/bootc-fetch-only.timer /etc/systemd/system/
RUN mkdir /var/opt/ && \
    echo "Not Ready" > /var/opt/ready.txt && \
    ln -sf /etc/systemd/system/bootc-fetch-only.timer /etc/systemd/system/timers.target.wants/bootc-fetch-only.timer

#Systemd container service
COPY files/etc-containers-systemd-demo-http.container /etc/containers/systemd/demo-http.container
RUN mkdir /opt/html/ && \
    echo "test-demo-message-1" >> /opt/html/index.html
